### PR TITLE
New modules

### PR DESCRIPTION
**Pull request by barrie0482**
Eric, 
some new modules using Nirsoft's FullEventLogView.exe to extract full event logs in csv format.

Cheers, Barrie

### CODE REVIEW

**Comment by EricZimmerman** [comment]
have you ensured the GUIDs are unique and these pass validation via kape.exe --mlist ?

**Comment by barrie0482** [comment]
Hi Eric,
All new guids created with powershells new-guid cmdlet. I checked the guids for all current modules plus my new ones for duplicates. See attached spreadsheet. 
[modules_guid.xlsx](https://github.com/EricZimmerman/KapeFiles/files/2949061/modules_guid.xlsx)
All modules have been validated via kape.exe --mlist. See attached txt file.
[Modules-mlist.txt](https://github.com/EricZimmerman/KapeFiles/files/2949062/Modules-mlist.txt)

 I have included the BinaryUrl property pointing to the download location.
All other info including requirements, etc. are documented at the end of the module in comment blocks.

I'll send through another pull request with a couple of minor EOL changes and a BinaryUrl  property I missed in one of the modules.

Cheers, Barrie

**Comment by barrie0482** [comment]
Eric,
Can you please hold off merging these. I have been doing some more testing and I am getting empty out files when I run it against the output from the files copied using the target options. I need to work out what I've done wrong. I'll submit a pull request when I've worked out the problem.
Sorry about the taking up your time.

Cheers, Barrie

**Comment by EricZimmerman** [comment]
Ok sounds good. Adding the debug and trace options ate very useful when
doing work like this because you can see what files are found, matches, and
the processors output as it runs.

Eric Zimmerman

Opinions stated, unless explicitly stated otherwise, are mine and not that
of my employer.

P // 501-313-3778

**Comment by barrie0482** [comment]
Hi Eric,
I found what was causing my empty output files. I have updated the command lines and the comments at the bottom of the modules relating to usage. I have also updated the Hindsight and the srum-dump modules in a similar way. I have not included those in this lot as I am not sure if I should contact the authors of those modules first. I am looking at writing a shellbags module next.

Cheers, Barrie

**Comment by EricZimmerman** [comment]
thanks!!!

**Comment by EricZimmerman** [comment]
i probably would hit up those others fot their modules, especially if you improved things, fixed things, etc

**Pull request merged**
