### PR TITLE
Add tool sync module for various EZ tools

### PR DESCRIPTION
**Pull request by Karneades**
## Description

Add tool sync module for various EZ tools. See https://github.com/EricZimmerman/KapeFiles/issues/406 for discussion. Currently including the following already existing individual sync modules
* RECmd_Sync.mkape
* EvtxECmd_Sync.mkape
* SQLECmd_Sync.mkape

## Checklist:
Please replace every instance of `[ ]` with `[X]`

- [x] I have generated a unique GUID for my Target(s)/Module(s)
- [x] I have placed the Target/Module in an appropriate subfolder in Targets or Modules. If one doesn't exist, I have either added it to the Misc folder or created a relevant subfolder **with justification**
- [x] I have set or updated the version of my Target(s)/Module(s)
- [x] I have verified that KAPE parses the Target successfully via kape.exe, using `--tlist`/`--mlist` and corrected any errors 
- [ ] I have consulted either the [Target Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/TargetGuide.guide), [Target Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/TargetTemplate.template), [Compound Target Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/CompoundTargetGuide.guide), or [Compound Target Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/CompoundTargetTemplate.template) to ensure my Target(s) follow the same format

Thank you for your submission and for contributing to the DFIR community!

### CODE REVIEW

**Comment by rathbuna** [comment]
@Karneades thoughts on including `kape.exe --sync` to this one as well? 

@EricZimmerman I know there's a nice big button for Sync with GitHub on gkape but thoughts on including a Module for Kape_Sync as a part of this consolidation effort of tool syncing within a single Module?

**Comment by Karneades** [comment]
yeah, I would like to add the KAPE sync as well (now or in the future) to allow the update also from this sync module. I have to test first how kape.exe running a module triggering kape.exe for the sync behaves.

**Comment by rathbuna** [comment]
> 
> 
> yeah, I would like to add the KAPE sync as well (now or in the future) to allow the update also from this sync module. I have to test first how kape.exe running a module triggering kape.exe for the sync behaves.

It runs just fine. I have a local module for this already made on my machine so I can throw it on the repo if all agree it's a good thing to add for this one. I think it makes sense given it's a separate Module itself and not baked into the other Modules, like RECmd, etc. I think once this gets sorted out and PR'd, we can remove any --sync Modules from being baked into tool-specific Modules, like RECmd, EVTXECmd, etc.

**Comment by EricZimmerman** [comment]
As a rule, do you think we should start all of these with sync and then what the sync is for? That way everything would end up grouped together

**Comment by rathbuna** [comment]
Ahh so you mean like Description would be Sync: EVTXECmd, Sync: RECmd, etc, for the purposes of sorting.

**Comment by Karneades** [comment]
I think the filenames should be like that, Eric means? 

Sync_KAPE
Sync_RECmd
...

**Comment by rathbuna** [comment]
Ah yes, that works too, re: filename. 

Re: subfolders, Modules are going to be reorganized in the near future much like how Targets were recently so that will be address at that time.

**Comment by rathbuna** [comment]
https://github.com/EricZimmerman/KapeFiles/pull/416 has now renamed all tool sync Modules to Sync_TOOL.mkape.

**Comment by rathbuna** [comment]
@Karneades @EricZimmerman how about this? I think it looks pretty good and is a good start.

**Comment by Karneades** [comment]
Yeah, thanks!

**Review by rathbuna — APPROVED** [review]

**Pull request merged**
