### PR TITLE
Add module to convert ROT13 encoded UserAssist keys

### PR DESCRIPTION
**Pull request by Karneades**
## Description

This module converts the ROT13 encoded UserAssist values found in the output of RECmd_UserActivity.mkape (*\_RECmd\_Batch\_UserActivity\_Output.csv) into correct usable values. Otherwise, the UserAssist entries are of lesser value, because in the CSV only encoded values are found.

The module can be used manually after running RECmd_UserActivity.mkape or we can add it to the RECmd compound (I would prefer that), if of value for others too, that it is automatically called after running the UserActivity command.

The output file is \<OriginalFilename\>_converted.csv but the module could also overwrite the original file, if that's better, then I will propose the needed change, of course.

The first part of the command is only the function for ROT13 conversion to omit the use of an external PowerShell script. After $files... the search and replace is implemented. All ValueName fields on UserAssist lines in the found REcmd output files are then converted. ROT13 function taken from https://behindthebits.blogspot.com/2014/12/rot13-in-powershell.html and made a one-liner.

## Checklist:
Please replace every instance of `[ ]` with `[X]`

- [x] I have generated a unique GUID for my Target(s)/Module(s)
- [x] I have placed the Target/Module in an appropriate subfolder in Targets or Modules. If one doesn't exist, I have either added it to the Misc folder or created a relevant subfolder **with justification**
- [x] I have set or updated the version of my Target(s)/Module(s)
- [x] I have verified that KAPE parses the Target successfully via kape.exe, using `--tlist`/`--mlist` and corrected any errors 
- [ ] I have consulted either the [Target Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/TargetGuide.guide), [Target Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/TargetTemplate.template), [Compound Target Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/CompoundTargetGuide.guide), or [Compound Target Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/CompoundTargetTemplate.template) to ensure my Target(s) follow the same format

Thank you for your submission and for contributing to the DFIR community!

### CODE REVIEW

**Comment by EricZimmerman** [comment]
why do this? use batch mode against those ,which will then invoke the plugin, auto unrot13ing and pulling other data out of the userassist keys

**Comment by EricZimmerman** [comment]
the main csv should have the decoded values in it, as should the plugin specific batch file

**Comment by EricZimmerman** [comment]
you are seeing both the encoded value and the decoded value because the encoded value is the tie back to the original value in the Registry

**Comment by rathbuna** [comment]
This is already done with the RECmd Batch files, particularly the UserActivity.reb and the RECmd_Batch_MC.reb files. 
image

**Comment by Karneades** [comment]
I don't have those plugin information in my output csv. User issue again, I guess. I have recmd version 1.6, plugin and batchexamples directories, but missing those plugin information.

**Comment by rathbuna** [comment]
@Karneades what command are you running? Are you running RECmd by itself? KAPE Module? Make sure you Sync with GitHub as some automation with syncing was added today in the Modules. That way you'll know you're always running the latest and greatest. There's got to be a reason you're not seeing it so let's figure it out together. Let me know.

**Comment by Karneades** [comment]
I run it using KAPE module and missed the important error message, which I got now when running RECmd itself... oh my... I downloaded the newest RECmd package today and missed unlocking the DLL files.. I got now a "error loading plugin" and then thought but why, I have all these files... and then came to the file unlock issue after downloading these files. Now I have everything on the CSV. Awesome!

Fazit: Unlock of the .dll was needed and I could instead improve other things than building and hacking a needles module (facepalm).

**Comment by EricZimmerman** [comment]
you most likely used Windows to unzip things, which blocks the DLLs.

never use Windows to do that, always use 7zip or Winrar, etc.

**Pull request closed without merging**
