### PR TITLE
Create IIS.tkape

### PR DESCRIPTION
**Pull request by reynas**
At the moment it is just collecting the web.config files from the default directory for websites, which of course is not always going to be correct. The applicationHost.config file will give the actual location of websites though.

## Description

Please include a summary of the change and (if applicable) which issue is fixed.

## Checklist:
Please replace every instance of `[ ]` with `[X]` OR click on the checkboxes after you submit your PR

- [X] I have generated a unique `GUID` for my Target(s)/Module(s)
- [X] I have placed the Target(s)/Module(s) in an appropriate subfolder in Targets or Modules. If one doesn't exist, I have either added it to the `Misc` folder or created a relevant subfolder **with justification**
- [X] I have set or updated the version of my Target(s)/Module(s)
- [X] I have verified that KAPE parses the Target(s)/Module(s) successfully via kape.exe, using `--tlist`/`--mlist` and corrected any errors 
- [X] I have validated my Target(s)/Module(s) against test data and verified they are working as intended
- [X] I have made an attempt to document the artifacts within the Target(s) or Module(s) I am submitting. If documentation doesn't exist, I have placed `N/A` underneath the Documentation header
- [X] For Targets, I have consulted either the [Target Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/TargetGuide.guide), [Target Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/TargetTemplate.template), [Compound Target Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/CompoundTargetGuide.guide), or [Compound Target Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/CompoundTargetTemplate.template) to ensure my Target(s) follow the same format
- [ ] For Modules, I have consulted either the [Module Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/ModuleGuide.guide), [Module Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/ModuleTemplate.template), [Compound Module Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/CompoundModuleGuide.guide), or [Compound Module Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/CompoundModuleTemplate.template) to ensure my Module(s) follow the same format

If your submission involves an SQLite database, have you considered making an [SQLECmd Map](https://github.com/EricZimmerman/SQLECmd/tree/master/SQLMap/Maps) for the SQLite database? If you make a Map, please add the SQLite database to the [SQLiteDatabases.tkape Compound Target](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Compound/SQLiteDatabases.tkape).

Thank you for your submission and for contributing to the DFIR community!

### CODE REVIEW

**Comment by AndrewRathbun** [comment]
Is there a better name for this than simply IIS? Could this be merged with the IISLogs Target found in the Logs folder? Shouldn't this go in the Windows folder instead of Apps since it's a Windows artifact?

**Comment by reynas** [comment]
> Is there a better name for this than simply IIS? Could this be merged with the IISLogs Target found in the Logs folder? Shouldn't this go in the Windows folder instead of Apps since it's a Windows artifact?

I honestly had the same thoughts. I took this road because "Exchange" was listed in Apps as well.
I would've gone for Windows at first if it was not for the "Exchange" target in Apps.

**Comment by AndrewRathbun** [comment]
> > Is there a better name for this than simply IIS? Could this be merged with the IISLogs Target found in the Logs folder? Shouldn't this go in the Windows folder instead of Apps since it's a Windows artifact?
> 
> I honestly had the same thoughts. I took this road because "Exchange" was listed in Apps as well.
> I would've gone for Windows at first if it was not for the "Exchange" target in Apps.

That's an easy fix. I can move that. Thanks for the heads up on that!

**Comment by AndrewRathbun** [comment]
> > > Is there a better name for this than simply IIS? Could this be merged with the IISLogs Target found in the Logs folder? Shouldn't this go in the Windows folder instead of Apps since it's a Windows artifact?
> > 
> > 
> > I honestly had the same thoughts. I took this road because "Exchange" was listed in Apps as well.
> > I would've gone for Windows at first if it was not for the "Exchange" target in Apps.
> 
> That's an easy fix. I can move that. Thanks for the heads up on that!

https://github.com/EricZimmerman/KapeFiles/commit/bd50b59c0644e13bddfef95bb6b7d6f0d3b53bbe

This is done

**Comment by AndrewRathbun** [comment]
@reynas do you think this Target could be merged with https://github.com/EricZimmerman/KapeFiles/blob/f99e6d98563a2a5c9a3a04c3f8dbe1f3733e45bf/Targets/Logs/IISLogFiles.tkape? Or is there enough of a reason to have these paths separate? If separate, should we rename this Target to IIS***.tkape, where `***` is something descriptive of whats being pulled?

**Comment by reynas** [comment]
I would keep it separate if it was up to me. The same kind of targets could be created for Apache config, Nginx config, ... (while the log collection targets already exist for those as well). We could rename it to IISConfiguration I guess? Just my two cents.

**Comment by AndrewRathbun** [comment]
@reynas I changed the name. Everything else good for you? Windows folder. New filename. Anything else before I merge?

**Comment by reynas** [comment]
Looking good, nothing else to add from my side.
Thanks for the effort!

**Review by AndrewRathbun — APPROVED** [review]

**Pull request merged**
