### PR TITLE
Add SBECmd.mkape

### PR DESCRIPTION
**Pull request by barrie0482**
Hi Eric,

I have added SBECmd.mkape. mlist has been performed. New guid created. Doco added in comments at end of file.

Cheers, Barrie.

### CODE REVIEW

**Comment by EricZimmerman** [comment]
hi

why do this:

CommandLine: -d %sourceDirectory%\Users\%username%\ --csv %destinationDirectory% -q

and not this:

CommandLine: -d %sourceDirectory% --csv %destinationDirectory% -q

sbecmd will find hives recursively. this also negates the need for username variable

also, do NOT symlink unless you need to. just put sbecmd.exe in the Modules\bin directory and it will work fine AND its portable

**Comment by barrie0482** [comment]
Hi Eric,

*sbecmd will find hives recursively. this also negates the need for
username variable*
Agreed. I have done a bit more testing and sbecmd provides identifying
information in the output filename.I will change the module.

*also, do NOT symlink unless you need to*
The first option in comments at the bottom of the module is;
*SBECmd.exe must be in Modules\bin* *folder *or

The second option is using the symlink. I like the symlink as I don't need
to have multiple copies of the tools. I have just one place to update when
updated tools arrive. I have removed the symlink option from the comments.

Cheers, Barrie

**Comment by barrie0482** [comment]
Updated SBECmd

**Comment by EricZimmerman** [comment]
looks good

**Pull request merged**
