### PR TITLE
Create Telegram.tkape

### PR DESCRIPTION
**Pull request by nembo81**
Hi,I'd like to pull a new target for Telegram desktop application.Thanks!

## Description

Please include a summary of the change and (if applicable) which issue is fixed.

## Checklist:
Please replace every instance of `[ ]` with `[X]`

- [x] I have generated a unique GUID for my target(s)/module(s)
- [X] I have placed the target/module in an appropriate subfolder in Targets or Modules. If one doesn't exist, I have either added it to the Misc folder or created a relevant subfolder **with justification**
- [X] I have verified that KAPE parses the target successfully via kape.exe, using `--tlist`/`--mlist` and corrected any errors.

### CODE REVIEW

**Comment by mdawsonuk** [comment]
Just wondering why you're pulling the whole Telegram directory from AppData - isn't that the executable files as well?

**Comment by nembo81** [comment]
Hi,you're right.With the whole folder you can run Telegram.exe from there and been already authenticated.I didn't have the chance to copy the data folder between two different releases, so I've included it to exclude any compatibility issues.

**Comment by mdawsonuk** [comment]
Ah okay that makes more sense - although maybe adding a more granular target down the road would be a good idea 🙂

**Comment by nembo81** [comment]
> Ah okay that makes more sense - although maybe adding a more granular target down the road would be a good idea 🙂

I totally agree and thanks for the suggestion.I'd like to test it with a very old Telegram version and if all is ok, I'll modify the target as well.

**Pull request merged**
