### PR TITLE
Create Gigatribe.tkape

### PR DESCRIPTION
**Pull request by dfirdoctor**
Added Gigatribe module

### CODE REVIEW

**Comment by EricZimmerman** [comment]
ah my old friend, Gigatribe.

**Comment by dfirdoctor** [comment]
If you have time to making your Gigtribe parsers (Gigatribe chat parser etc ) cli friendly we could do some modules for kape.  Den 21 maj 2019 14:44 skrev Eric <notifications@github.com>:ah my old friend, Gigatribe.

**Comment by EricZimmerman** [comment]
cant do that. far too much work =(

**Comment by dfirdoctor** [comment]
Gotta try, thanks anyway for great tools!Den 21 maj 2019 16:31 skrev Eric <notifications@github.com>:cant do that. far too much work =(

**Pull request merged**
