### PR TITLE
IBM Aspera Connect & FileZilla XML logs.

### PR DESCRIPTION
**Pull request by DReneau**
Greetings,
both Target files have a unique GUID and both have been tested within KAPE.

### CODE REVIEW

**Comment by EricZimmerman** [comment]
please confirm this is a unique guid and it passes a --tkape listing

thanks!

**Comment by DReneau** [comment]
Greetings, I can confirm that both have a unique guid and both pass the --tkape listing. Thank you.

**Comment by EricZimmerman** [comment]
ok, you need to repull from me to get the new folder layout, then move the new targets to the appropriate subfolder, like logs or apps, etc

**Comment by EricZimmerman** [comment]
closing until repushed into proper folder

**Pull request closed without merging**
