### PR TITLE
Add Cisco Jabber target file.

### PR DESCRIPTION
**Pull request by Mogibear**
Not sure how many people will find use out of this, but pulling Jabber chat logs could be helpful for anyone who uses it in their enterprise.

### CODE REVIEW

**Comment by EricZimmerman** [comment]
have you verified these via kape.exe --tlist to make sure the YAML is clean?

**Comment by EricZimmerman** [comment]
and the GUID is unique yes?

**Comment by Mogibear** [comment]
Verified via --tlist and it shows up clean. Just made an edit to make sure GUID was unique.

**Comment by EricZimmerman** [comment]
thanks!

**Pull request merged**
