### PR TITLE
Update SRUMDump.mkape to use newest version of tool

### PR DESCRIPTION
**Pull request by vxsh4d0w**
## Description

Please include a summary of the change and (if applicable) which issue is fixed.

## Checklist:
Please replace every instance of `[ ]` with `[X]` OR click on the checkboxes after you submit your PR

- [X] I have generated a unique `GUID` for my Target(s)/Module(s)
- [X] I have placed the Target(s)/Module(s) in an appropriate subfolder in Targets or Modules. If one doesn't exist, I have either added it to the `Misc` folder or created a relevant subfolder **with justification**
- [X] I have set or updated the version of my Target(s)/Module(s)
- [X] I have verified that KAPE parses the Target(s)/Module(s) successfully via kape.exe, using `--tlist`/`--mlist` and corrected any errors 
- [X] I have validated my Target(s)/Module(s) against test data and verified they are working as intended
- [X] I have made an attempt to document the artifacts within the Target(s) or Module(s) I am submitting. If documentation doesn't exist, I have placed `N/A` underneath the Documentation header
- [ ] For Targets, I have consulted either the [Target Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/TargetGuide.guide), [Target Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/TargetTemplate.template), [Compound Target Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/CompoundTargetGuide.guide), or [Compound Target Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/CompoundTargetTemplate.template) to ensure my Target(s) follow the same format
- [X] For Modules, I have consulted either the [Module Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/ModuleGuide.guide), [Module Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/ModuleTemplate.template), [Compound Module Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/CompoundModuleGuide.guide), or [Compound Module Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/CompoundModuleTemplate.template) to ensure my Module(s) follow the same format

If your submission involves an SQLite database, have you considered making an [SQLECmd Map](https://github.com/EricZimmerman/SQLECmd/tree/master/SQLMap/Maps) for the SQLite database? If you make a Map, please add the SQLite database to the [SQLiteDatabases.tkape Compound Target](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Compound/SQLiteDatabases.tkape).

Thank you for your submission and for contributing to the DFIR community!

### CODE REVIEW

**Comment by AndrewRathbun** [comment]
@vxsh4d0w is this the same as https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Apps/GitHub/SRUMDump.mkape ?

**Comment by EricZimmerman** [comment]
this tool is way slower than my tool fyi. i wouldnt recommend it. is there something this does that mine does not?

**Comment by vxsh4d0w** [comment]
> @vxsh4d0w is this the same as https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Apps/GitHub/SRUMDump.mkape ?

It's mkape module with new version of srum_dump (https://github.com/MarkBaggett/srum-dump).

**Comment by AndrewRathbun** [comment]
> > @vxsh4d0w is this the same as https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Apps/GitHub/SRUMDump.mkape ?
> 
> It's mkape module with new version of srum_dump (https://github.com/MarkBaggett/srum-dump).

Okay, thanks for that context. I think we should just update the existing Module and increment the version. Unless there is a reason I'm not aware of to keep the Module around for an outdated version of that tool, that's typically how Modules have evolved in the past as tools get updated and switches/parameters evolve. Thoughts?

**Comment by vxsh4d0w** [comment]
> > > @vxsh4d0w is this the same as https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Apps/GitHub/SRUMDump.mkape ?
> > 
> > 
> > It's mkape module with new version of srum_dump (https://github.com/MarkBaggett/srum-dump).
> 
> Okay, thanks for that context. I think we should just update the existing Module and increment the version. Unless there is a reason I'm not aware of to keep the Module around for an outdated version of that tool, that's typically how Modules have evolved in the past as tools get updated and switches/parameters evolve. Thoughts?

I agree with you. So, may i  update existing module?

**Comment by AndrewRathbun** [comment]
> > > > @vxsh4d0w is this the same as https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Apps/GitHub/SRUMDump.mkape ?
> > > 
> > > 
> > > It's mkape module with new version of srum_dump (https://github.com/MarkBaggett/srum-dump).
> > 
> > 
> > Okay, thanks for that context. I think we should just update the existing Module and increment the version. Unless there is a reason I'm not aware of to keep the Module around for an outdated version of that tool, that's typically how Modules have evolved in the past as tools get updated and switches/parameters evolve. Thoughts?
> 
> I agree with you. So, may i update existing module?

Yes, please do! GitHub has the benefit of commit history so we can always see what the commands were in the past by reviewing past commits. 

Feel free to keep this PR open, or you can close it. Either way, ping me when you're ready for me to take a look and merge.

**Comment by vxsh4d0w** [comment]
> > > > > @vxsh4d0w is this the same as https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Apps/GitHub/SRUMDump.mkape ?
> > > > 
> > > > 
> > > > It's mkape module with new version of srum_dump (https://github.com/MarkBaggett/srum-dump).
> > > 
> > > 
> > > Okay, thanks for that context. I think we should just update the existing Module and increment the version. Unless there is a reason I'm not aware of to keep the Module around for an outdated version of that tool, that's typically how Modules have evolved in the past as tools get updated and switches/parameters evolve. Thoughts?
> > 
> > 
> > I agree with you. So, may i update existing module?
> 
> Yes, please do! GitHub has the benefit of commit history so we can always see what the commands were in the past by reviewing past commits.
> 
> Feel free to keep this PR open, or you can close it. Either way, ping me when you're ready for me to take a look and merge.

Done. I'm pulling the request. Please delete previous one just to avoid any mess. Thanks again.

**Review by vxsh4d0w — COMMENTED** [review]
Fixed erros

**Comment by vxsh4d0w** [comment]
> this tool is way slower than my tool fyi. i wouldnt recommend it. is there something this does that mine does not?

Yes. I cannot win a challenge with you lol :D I wished just to update the mkape module that was based on a old version of srum_dump :) I like to support this project.

**Pull request merged**
