### PR TITLE
New Target - SoftPerfect Nework Scanner 'Netscan'

### PR DESCRIPTION
**Pull request by cert-cwatch**
## Description

This target will fetch the default output of the network scanning tool "Netscan". 
This tool is frequently observed in cases where threat actors neglect to delete its output.

Since this file contains valuable information, such as previously compromised hosts and the credentials used, it enables us to rapidly identify the compromised scope. 

## Checklist:

- [X] I have generated a unique `GUID` for my Target(s)/Module(s)
- [X] I have placed the Target(s)/Module(s) in an appropriate subfolder in Targets or Modules. If one doesn't exist, I have either added it to the `Misc` folder or created a relevant subfolder **with justification**
- [X] I have set or updated the version of my Target(s)/Module(s)
- [X] I have verified that KAPE parses the Target(s)/Module(s) successfully via kape.exe, using `--tlist`/`--mlist` and corrected any errors 
- [X] I have validated my Target(s)/Module(s) against test data and verified they are working as intended
- [X] I have made an attempt to document the artifacts within the Target(s) or Module(s) I am submitting. If documentation doesn't exist, I have placed `N/A` underneath the Documentation header
- [X] For Targets, I have consulted either the [Target Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/TargetGuide.guide), [Target Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/TargetTemplate.template), [Compound Target Guide](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/CompoundTargetGuide.guide), or [Compound Target Template](https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/CompoundTargetTemplate.template) to ensure my Target(s) follow the same format

### CODE REVIEW

**Comment by AndrewRathbun** [comment]
Thoughts on adding `C:\Users\%user%\AppData\Roaming\SoftPerfect Network Scanner\netscan.xml` to the Target? I use it legitimately and this is where `netscan.xml` resides @cert-cwatch

**Comment by AndrewRathbun** [comment]
Honestly, great question! I am unsure if regex can be leveraged within `Path:`, but I know it can for `FileMask:`. This would be a good question for @EricZimmerman

**Comment by EricZimmerman** [comment]
no, not path, just the filename.

if you want recursive, its gonna be a walk of everything

OR you pull the MFT via kape and then look thru the csv

**Comment by EricZimmerman** [comment]
another pivot is prefetch, and narrowing down the path from there

**Comment by cert-cwatch** [comment]
Thank you for your response.
I agree that searching for specific .xml files via the MFT / Prefetch is the better approach for our questions.

Can we at least merge to implement the search specifically for the netscan.xml file?

**Comment by EricZimmerman** [comment]
yea @AndrewRathbun can verify that all looks good

**Review by AndrewRathbun — APPROVED** [review]

**Pull request merged**
